-- MySQL Script generated by MySQL Workbench
-- Sat 30 Sep 2023 07:53:45 PM +0630
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TrainingDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TrainingDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrainingDB` ;
USE `TrainingDB` ;

-- -----------------------------------------------------
-- Table `TrainingDB`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainingDB`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `TrainingDB`.`secret_keys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainingDB`.`secret_keys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key_name` VARCHAR(255) NULL DEFAULT NULL,
  `is_used` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_name` (`key_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `TrainingDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainingDB`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `TrainingDB`.`user_register_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainingDB`.`user_register_course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `course_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_register_course_ibfk_1` (`user_id` ASC) VISIBLE,
  INDEX `user_register_course_ibfk_2` (`course_id` ASC) VISIBLE,
  CONSTRAINT `user_register_course_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TrainingDB`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_register_course_ibfk_2`
    FOREIGN KEY (`course_id`)
    REFERENCES `TrainingDB`.`courses` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
